### ISSUE TITLE
add content to your README

### ISSUE THREAD

**Issue by BarkleyBG** [bcjaeger/UNC-BIOS-Dissertation-Tex-Template#1]
You should add more content to the README to illustrate

1. what this repo was created to do
1. an example of how to use the items in this repo

For example, check out [our very similar repo](https://github.com/TarHeelBiostatistics/DoctoralThesisTexTemplate), or of course [hadley's dplyr repo](https://github.com/tidyverse/dplyr)

**Comment by bcjaeger** [comment]
Fixed! Thank you, Sir.
